version: '3.0'

services:
    db:
        container_name: userServiceDB
        image: mysql
        volumes:
            -   type: volume
                source: userservice-db-data
                target: /var/lib/mysql
                volume:
                    nocopy: true
        ports:
        -   3306:3306
        environment:
            - MYSQL_DATABASE=userservice
            - MYSQL_ALLOW_EMPTY_PASSWORD=true

volumes:
    userservice-db-data:
