version: '3.0'

services:
    userService:
        container_name: aTeamUserManagement
        image: ateam/usermanagement:latest
        ports:
            - 9084:9080
            - 9447:9443
        depends_on:
            - userDB
        environment:
            - DB_NAME=usermanagement
            - DB_HOST=userDB
            - DB_PORT=3306
            - DB_USER=root
            - DB_PW=
            - WAIT_HOSTS=userDB:3306
            - WAIT_HOSTS_TIMEOUT=60
            - WAIT_SLEEP_INTERVAL=5
        command: sh -c "/wait && /opt/ol/wlp/bin/server run defaultServer"
    userDB:
        container_name: aTeamUserManagementDB
        image: ateam/userdb:latest
        environment:
            - MYSQL_DATABASE=usermanagement
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        ports:
            - 3306:3306
    pizzaShop:
        container_name: aTeamPizzaShop
        image: ateam/pizzashop:latest
        ports:
            - 9083:9080
            - 9446:9443
        depends_on:
            - pizzaDB
        environment:
            - DB_NAME=pizzashop
            - DB_HOST=pizzaDB
            - DB_PORT=3306
            - DB_USER=root
            - DB_PW=
            - USER_SERVICE_PATH=http://userService:9080
            - WAIT_HOSTS=pizzaDB:3306
            - WAIT_HOSTS_TIMEOUT=60
            - WAIT_SLEEP_INTERVAL=5
        command: sh -c "/wait && /opt/ol/wlp/bin/server run defaultServer"
    pizzaDB:
        container_name: aTeamPizzaShopDB
        image: ateam/pizzashopdb:latest
        environment:
            - MYSQL_DATABASE=pizzashop
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        ports:
            - 3307:3306
    logisticsService:
        container_name: aTeamLogisticsService
        image: ateam/logisticsservice:latest
        ports:
            - 9081:9080
            - 9444:9443
        depends_on:
            - userService
        environment:
            - USER_SERVICE_PASSWORD=ferwfrwe435gsd
            - USER_SERVICE_PATH=http://userService:9080
    procurementService:
        container_name: aTeamProcurementService
        image: ateam/procurementservice:latest
        ports:
            - 9082:9080
            - 9445:9443
    pizzaProduction:
        container_name: aTeamPizzaProduction
        image: ateam/pizza-production:latest
        ports:
            - 9085:9080
            - 9448:9443
        environment:
            - PROCUREMENT_INTERN_URI=http://procurementService:9080/
            - LOGISTICS_INTERN_URI=http://logisticsService:9080/
