version: '3.0'

services:
    db:
        container_name: userManagementDB
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            -   type: volume
                source: usermanagement-db-data
                target: /var/lib/mysql
                volume:
                    nocopy: true
        ports:
        -   3306:3306
        environment:
            - MYSQL_DATABASE=usermanagement
            - MYSQL_ALLOW_EMPTY_PASSWORD=true

volumes:
    usermanagement-db-data:
